apiVersion: batch/v1
kind: Job
metadata:
  name: write-data
  namespace: kubeflow
  labels:
    app: write-data
spec:
  # -------------------------------------------------
  # This is used for creating connections ...
  # This doesn't need connections at the momnent
  # -------------------------------------------------
  selector:
    matchLabels:
      app: write-data # All pods/deployments that match label app=nginx to create a connection
  template:
    # -----------------------------------------------
    # This entire configuration is associated with
    # a pod. Config within a config
    # -----------------------------------------------
    metadata:
      labels:
        app: write-data # These are just labels
    # -----------------------------------------------
    # Blueprint for a pod ...
    # -----------------------------------------------
    spec:
      containers:
        - name: write-data
          image: omolluska/test-kubeflow-write-data:latest
          imagePullPolicy: IfNotPresent
          command: ["python3"]
          args: ["program.py"]
          volumeMounts:
            - mountPath: "/pipelines/component/src/data"
              name: volume-to-read-from-001
      imagePullSecrets:
        - name: docker-secret-kube
      restartPolicy: Never
      volumes:
        - name: volume-to-read-from-001
          persistentVolumeClaim: 
            claimName: pvc0001
