apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx # This makes a connection between a deployment/pods
  ports:
    - protocol: TCP
      port: 80 # port exposed to outside
      targetPort: 8080 # port of the target pod/deployment